name: deploy


on: 
  push:
    branches:
      - main
      - tryfixdeploy.yml

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node_version: 15.8.0

      - name: Setup Env
        run: npm install 

      - name: Test app
        run: ./node_modules/.bin/elm-test --compiler ./node_modules/.bin/elm
      
      - name: build elm-app
        run: 
          ./node_modules/.bin/elm make src/Main.elm

      - name: move index.html to public
        run:
          mv ./index.html ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

